import 'vuetify/styles'
import { createVuetify } from 'vuetify'
import { id } from 'vuetify/locale'
import { aliases, mdi } from 'vuetify/iconsets/mdi-svg'
import {
  mdiAccount,
  mdiAccountCash,
  mdiAccountCashOutline,
  mdiAccountOutline,
  mdiAlert,
  mdiBarcode,
  mdiBarcodeScan,
  mdiCalendar,
  mdiCalendarMonth,
  mdiCalendarMonthOutline,
  mdiCalendarOutline,
  mdiCar,
  mdiCarBattery,
  mdiCarCog,
  mdiCardAccountDetails,
  mdiCardAccountDetailsOutline,
  mdiCarEstate,
  mdiCarInfo,
  mdiCarLiftedPickup,
  mdiCarOutline,
  mdiCarSearch,
  mdiCarSearchOutline,
  mdiCarSettings,
  mdiCash,
  mdiCash100,
  mdiCashMinus,
  mdiCashPlus,
  mdiCashSync,
  mdiChartBox,
  mdiChartBoxOutline,
  mdiClipboardList,
  mdiClipboardListOutline,
  mdiClipboardText,
  mdiClipboardTextOutline,
  mdiCog,
  mdiCogOutline,
  mdiEmail,
  mdiEmailOutline,
  mdiFolderWrench,
  mdiFolderWrenchOutline,
  mdiGasStation,
  mdiGasStationOutline,
  mdiHammerWrench,
  mdiHome,
  mdiHomeOutline,
  mdiLock,
  mdiLockOutline,
  mdiOfficeBuilding,
  mdiOfficeBuildingMarker,
  mdiOfficeBuildingMarkerOutline,
  mdiOfficeBuildingOutline,
  mdiPalette,
  mdiPaletteOutline,
  mdiPencil,
  mdiPhone,
  mdiPhoneOutline,
  mdiScaleBalance,
  mdiScaleUnbalanced,
  mdiShipWheel,
  mdiSteering,
  mdiTag,
  mdiTagOutline,
  mdiTextBox,
  mdiTextBoxOutline,
  mdiTextBoxSearch,
  mdiTextBoxSearchOutline,
  mdiTools,
  mdiTruck,
  mdiTruckOutline,
  mdiWrenchCog,
  mdiWrenchCogOutline,
  mdiCheckboxMarkedCircleOutline,
  mdiCloseCircleOutline,
  mdiAlertCircleOutline,
  mdiHelpCircleOutline,
  mdiPackageVariant,
  mdiOil,
  mdiOilLevel,
  mdiRepeat,
  mdiToggleSwitch,
  mdiToggleSwitchOff,
  mdiBell,
  mdiBellOff,
  mdiEye,
  mdiEyeOff,
} from '@mdi/js'

const vuetify = createVuetify({
  defaults: {
    global: {},
    VCard: {
      variant: 'flat',
      rounded: 'xl',
      color: 'surface',
    },
    VDivider: {
      color: 'transparent',
      opacity: 1,
      thickness: 2,
    },
    VBtn: {
      variant: 'elevated',
      rounded: 'xl',
      elevation: 4,
    },
    VTextField: {
      variant: 'solo',
      bgColor: 'surface',
      baseColor: 'background',
      hideDetails: true,
      rounded: 'xl',
    },
    VTextarea: {
      variant: 'solo',
      bgColor: 'surface',
      baseColor: 'background',
      hideDetails: true,
      rounded: 'xl',
    },
    VSelect: {
      variant: 'solo',
      bgColor: 'surface',
      baseColor: 'background',
      hideDetails: true,
      rounded: 'xl',
    },
    VDataTable: {
      mustSort: true,
      sortBy: [{ key: 'nomor', order: 'asc' }],
      itemsPerPage: 10,
      itemsPerPageOptions: [5, 10, 25, 50, 100, 200, -1],
    },
    VDatePicker: {
      color: 'secondary',
      bgColor: 'surface',
      rounded: 'xl',
      width: '100%',
      showAdjacentMonths: true,
    },
    VChip: {
      variant: 'flat',
      size: 'small',
      class: 'text-capitalize',
      rounded: 'lg',
    },
  },
  theme: {
    defaultTheme: 'light',
    themes: {
      light: {
        colors: {
          primary: '#1B5E20',
          secondary: '#4CAF50',
          background: '#212121',
          surface: '#FAFAFA',
          success: '#3F51B5',
          error: '#B71C1C',
          warning: '#F4511E',
          merah: 'F44336',
          pink: '#E91E63',
          purple: '#9C27B0',
          indigo: '#3F51B5',
          blue: '#2196F3',
          cyan: '#00BCD4',
          teal: '#009688',
          green: '#4CAF50',
          lime: '#CDDC39',
          yellow: '#FFEB3B',
          amber: '#FFC107',
          orange: '#FF9800',
          Brown: '#795548',
          grey: '#9E9E9E',
          white: '#FFFFFF',
          black: '#000000',
        },
        dark: false,
      },
    },
  },
  locale: {
    locale: 'id',
    fallback: 'id',
    messages: { id },
  },
  icons: {
    defaultSet: 'mdi',
    sets: { mdi },
    aliases: {
      //~1~DEVELOPMENT START
      // 'face-woman': mdiFaceWoman,
      // 'face-woman-outline': mdiFaceWomanOutline,
      //~1~DEVELOPMENT END
      ...aliases,
      email: mdiEmail,
      'email-outline': mdiEmailOutline,
      lock: mdiLock,
      'lock-outline': mdiLockOutline,
      home: mdiHome,
      'home-outline': mdiHomeOutline,
      account: mdiAccount,
      'account-outline': mdiAccountOutline,
      'mdi-checkbox': mdiCheckboxMarkedCircleOutline,
      'mdi-close': mdiCloseCircleOutline,
      'mdi-alert': mdiAlertCircleOutline,
      'mdi-help': mdiHelpCircleOutline,
      tools: mdiTools,
      'hammer-wrench': mdiHammerWrench,
      steering: mdiSteering,
      'ship-wheel': mdiShipWheel,
      car: mdiCar,
      oil: mdiOil,
      'oil-fill': mdiOilLevel,
      'car-outline': mdiCarOutline,
      'car-cog': mdiCarCog,
      'car-battery': mdiCarBattery,
      'cash-plus': mdiCashPlus,
      'cash-minus': mdiCashMinus,
      'cash-sync': mdiCashSync,
      'clipboard-text': mdiClipboardText,
      'clipboard-text-outline': mdiClipboardTextOutline,
      'text-box-search': mdiTextBoxSearch,
      'text-box-search-outline': mdiTextBoxSearchOutline,
      pencil: mdiPencil,
      statuses: mdiRepeat,
      phone: mdiPhone,
      'phone-outline': mdiPhoneOutline,
      alert: mdiAlert,
      info: mdiHelpCircleOutline,
      'card-account-details': mdiCardAccountDetails,
      'card-account-details-outline': mdiCardAccountDetailsOutline,
      'office-building': mdiOfficeBuilding,
      'office-building-outline': mdiOfficeBuildingOutline,
      'office-building-marker': mdiOfficeBuildingMarker,
      'office-building-marker-outline': mdiOfficeBuildingMarkerOutline,
      'account-cash': mdiAccountCash,
      'account-cash-outline': mdiAccountCashOutline,
      'car-lifted-pickup': mdiCarLiftedPickup,
      'car-search': mdiCarSearch,
      'car-search-outline': mdiCarSearchOutline,
      'car-info': mdiCarInfo,
      'gas-station': mdiGasStation,
      'gas-station-outline': mdiGasStationOutline,
      'purchase-status': mdiGasStation,
      'purchase-status-outline': mdiGasStationOutline,
      palette: mdiPalette,
      'palette-outline': mdiPaletteOutline,
      tag: mdiTag,
      'tag-outline': mdiTagOutline,
      package: mdiPackageVariant,
      'toggle-off': mdiToggleSwitchOff,
      'toggle-on': mdiToggleSwitch,
      cash: mdiCash,
      'cash-100': mdiCash100,
      'car-estate': mdiCarEstate,
      'car-settings': mdiCarSettings,
      cog: mdiCog,
      'cog-outline': mdiCogOutline,
      'folder-wrench': mdiFolderWrench,
      'folder-wrench-outline': mdiFolderWrenchOutline,
      'clipboard-list': mdiClipboardList,
      'clipboard-list-outline': mdiClipboardListOutline,
      'wrench-cog': mdiWrenchCog,
      'wrench-cog-outline': mdiWrenchCogOutline,
      'text-box': mdiTextBox,
      'text-box-outline': mdiTextBoxOutline,
      barcode: mdiBarcode,
      'barcode-scan': mdiBarcodeScan,
      'scale-balance': mdiScaleBalance,
      'scale-unbalance': mdiScaleUnbalanced,
      truck: mdiTruck,
      'truck-outline': mdiTruckOutline,
      calendar: mdiCalendar,
      'calendar-outline': mdiCalendarOutline,
      'calendar-month': mdiCalendarMonth,
      'calendar-month-outline': mdiCalendarMonthOutline,
      'chart-box': mdiChartBox,
      'chart-box-outline': mdiChartBoxOutline,
      'bell-active': mdiBell,
      'bell-passive': mdiBellOff,
      'account-active': mdiAccount,
      'account-passive': mdiAccountOutline,
      eye: mdiEye,
      'eye-off': mdiEyeOff,
    },
  },
})

export default vuetify
